### ISSUE TITLE
I have a little problem with design

### ISSUE THREAD

**Issue by stilic** [ausername-1/Dangerous-Users#1]
PLEASE, SWITCH FROM BULMA TO HOME-MADE CSS FRAMEWORK!!!! (ALSO, YOU SAY YOU HAVE A CSS FILE IN `src` FOLDER!!!)

**Comment by trentwiles** [comment]
![image](https://user-images.githubusercontent.com/59586759/113447042-167d0880-93c7-11eb-8e73-58ddeae51628.png)

**Comment by stilic** [comment]
ya!!!! L IS REAL!!!!!!

**Comment by ghost** [comment]
![804478104256380975](https://user-images.githubusercontent.com/51095261/113447063-cff8cf80-9401-11eb-9d2c-9f98f9e4860b.png)

**Comment by trentwiles** [comment]
![image](https://user-images.githubusercontent.com/59586759/113447090-2e548c80-93c7-11eb-846a-c9bc95ebfefd.png)

**Comment by ausername-1** [comment]
![skull](https://user-images.githubusercontent.com/81475574/113447105-e0a94580-9401-11eb-8ef6-ce7f833ede8f.png)

**Comment by trentwiles** [comment]
![image](https://user-images.githubusercontent.com/59586759/113447130-3b717b80-93c7-11eb-9958-2a7d65f62e05.png)

**Comment by ghost** [comment]
<img width="26" alt="813899009290010684" src="https://user-images.githubusercontent.com/51095261/113447132-e7d05380-9401-11eb-9c31-0868c0305977.png">

**Comment by islemci** [comment]
![](https://user-images.githubusercontent.com/51095261/113447063-cff8cf80-9401-11eb-9d2c-9f98f9e4860b.png)

**Comment by trentwiles** [comment]
![image](https://user-images.githubusercontent.com/59586759/113447156-4b895b00-93c7-11eb-9bfa-9ddcbd19b6ea.png)

**Comment by stilic** [comment]
please, kill @ausername-1 !!!!!

**Comment by stilic** [comment]
no

**Comment by islemci** [comment]
Who want some Ğ bucks

**Comment by stilic** [comment]
yes

**Comment by trentwiles** [comment]
growbux.net

**Comment by islemci** [comment]
freeğ.glitch.me

**Comment by stilic** [comment]
what

**Comment by islemci** [comment]
will not work

**Comment by trentwiles** [comment]
rats

**Comment by islemci** [comment]
no

**Comment by ghost** [comment]
<img width="60" alt="818132764725477429" src="https://user-images.githubusercontent.com/51095261/113447266-2cf48580-9402-11eb-9811-fa91af191c37.png">

**Comment by islemci** [comment]
Ğ bocks

**Comment by islemci** [comment]
Ben türküm naber

**Comment by ghost** [comment]
oh you speak turkish let me speak finnish

**Comment by islemci** [comment]
![Uploading 6F1AD38B-5541-4446-A0AD-F3F755D985F5.png…]()

**Comment by ghost** [comment]
VITTU SAATANAN KUSIPÄÄT LÄHTEKÄÄ HEVON VITTUUN!

**Comment by islemci** [comment]
> oh you speak turkish let me speak finnish

napmam lazım

**Comment by ghost** [comment]
haista vittu läski

**Comment by islemci** [comment]
> haista vittu läski

neden

**Comment by trentwiles** [comment]
bash but sh

SlayerBuyer — Today at 3:21 PM
Ğ

CEO of helpme.net — Today at 3:21 PM
ĞĞs

SlayerBuyer — Today at 3:21 PM
Soft G
[3:21 PM]
Ğ

ausername — Today at 3:21 PM
go make a pull request
[3:21 PM]
i'll accept it

**Comment by islemci** [comment]
who want learn torkish

**Comment by trentwiles** [comment]
who wants to learn americanish

**Comment by trentwiles** [comment]
https://scams.riverside.rocks
i forgot about this website

**Comment by islemci** [comment]
> who wants to learn americanish

ben

**Comment by stilic** [comment]
use https://stlix.noho.st/a/dangerous-users-chat/ instead
